### ISSUE TITLE
Redo new server member flow

### ISSUE THREAD

**Issue by gt-codes** [blaccsmith/blaccsmith#15]
## Using Embedded Buttons

- [Documentation](https://discordjs.guide/interactions/buttons.html#building-and-sending-buttons) on buttons
- Flow
  - New member joins the server
    - _They can only see the `#community-guidelines`  channels._
  - New member clicks button to accept guidelines
    - Bot replies with explicit instructions on how to use the /intro command with a gif
  - User uses /intro command
    - Keep current implementation of command

## Fallback if Embedded Buttons don't work
- Flow
  - New member joins the server
    - _They can only see the `#community-guidelines`  channels._
  - New member clicks button to accept guidelines
    - Give new member the `Onboarding` role
    - Bot tags the new member in the `#onboarding` channel saying _"Check the pinned message 👆🏿 for instructions on how to use the slash command so you can introduce yourself and get access to all channels 😎"_
      - `#onboarding` should have the pinned message with instructions on using the /intro command
  - User uses `/intro` command
    - _Keep current implementation of command_
    - Find message in `#onboarding` where the author id matches the user's id and delete that message

**Comment by Genyus** [comment]
Closed by #20
